### ISSUE TITLE
Investigate potential pandas 2.0 speedup

### ISSUE THREAD

**Issue by juliangaal** [NinaWie/dav_hut_finder#13]

**Comment by NinaWie** [comment]
I'm already using pandas 2.0 and it should be installed by default - can we close this issue?

**Comment by juliangaal** [comment]
https://github.com/NinaWie/dav_hut_finder/blob/bae48fb823196eb161e825897756c607b0bd6e9a/backend/pyproject.toml#L20

you are right, geopandas 1.0.1 installs pandas 2.2.3, I probably confused the two packages
